### ISSUE TITLE
run_container_create_given_capacity doesn't check size

### ISSUE THREAD

**Issue by WojciechMula** [RoaringBitmap/CRoaring#101] opened 2017-05-09 17:17 UTC
The function **run_container_create_given_capacity** (https://github.com/RoaringBitmap/CRoaring/blob/master/src/containers/run.c#L70) doesn't check its argument and it's possible to pass zero size. According to the C standard, malloc(0) might return NULL or a non-NULL pointer (which can be only passed to free). For instance, GLIBC returns the pointer.

As I checked, the function is feed with the value returned from function **array_container_number_of_runs**, which may be 0.

**Comment by lemire** [comment] 2017-05-09 17:30
I think ``malloc(0)`` is safe in C. Of course, you can only access 0 byte in the resulting memory array.

**Comment by WojciechMula** [comment] 2017-05-09 17:42
I used to think so, but it seems not safe: https://www.securecoding.cert.org/confluence/display/c/MEM04-C.+Beware+of+zero-length+allocations

**Comment by lemire** [comment] 2017-05-09 17:45
I don't understand where the problem is. Do you?

They say...

>In cases where the memory allocation functions return a non-null pointer, reading from or writing to the allocated memory area results in undefined behavior.

Duh.

Of course if you write...

      char * x = malloc(0);
      x[0] = 1;

... the result is undefined. That's because it is buggy code.

**Comment by WojciechMula** [comment] 2017-05-09 18:08
I was concerned with reading/writing memory in way you shown. I'm not saying it is a serious issue, just pointing out a possible problem.

**Comment by owenkaser** [comment] 2017-05-09 18:36
I suppose it could behave as if you had requested several GB of
memory...after some  of these allocations that you can't use, you'll run
out of memory.

I wonder if this is new.  I thought for years that malloc(0) was known to
be safe.  Maybe it was just documented as safe on whatever platforms I was
using, as opposed to being addressed in the standard.

**Comment by lemire** [comment] 2017-05-09 20:04
@owenkaser  @WojciechMula 

I committed something which should alleviate concerns...

https://github.com/RoaringBitmap/CRoaring/commit/efa1d97d3817d83bd19b7ef5f9b991ead3d7005c


Still. Maybe we need to discuss this.

1. If you write code that can do  ``size_t alloc = 0; char * x = malloc(alloc); x[0] = 1;`` through some logic, then the logic is wrong and the code is buggy. I don't think you can blame ``malloc`` and you should just fix the logic bug.

2. One potential issue is that, in the code, we use `` char * x = malloc(alloc); if (x == NULL) ...`` to check that the ``malloc`` call was successful. This is a problem if ``alloc`` can be zero because, on some systems, then this will lead the code to always assume that the allocation failed. However, I think it is only a theoretical concern because I could not find any system where ``malloc(0)`` does return the NULL pointer. 

You can try it out on your favorite system:

```
#include <malloc.h>
#include <stdio.h>
#include <inttypes.h>

int main() {
  printf("0x%" PRIXPTR "\n", (uintptr_t)malloc(0));
}
```

**Closed by lemire** 2017-05-09 20:04 UTC

**Comment by lemire** [comment] 2017-05-09 20:12
See https://github.com/RoaringBitmap/CRoaring/issues/94
