### ISSUE TITLE
[Q] Question about `extern inline` defined in CRoaring

### ISSUE THREAD

**Issue by arthurkiller** [RoaringBitmap/CRoaring#325] opened 2021-11-25 06:30 UTC
We have faced a compile bug about `extern inline` while using `roaring.cpp` generated by `amalgamation.sh`.

we are on `v0.3.4`.

> roaring.c : 15003
> extern inline bool roaring_bitmap_contains(const roaring_bitmap_t *r, uint32_t val);
>
> defined in same file roaring.c: 17665

this function is defined in the same source file. We have fixed this by removing this statement.

And, by the way, do we really need `extern inline` together for the function definition?
> https://stackoverflow.com/questions/216510/what-does-extern-inline-do

**Comment by lemire** [comment] 2021-11-25 16:55
> And, by the way, do we really need extern inline together for the function definition?

We do. You can verify that build failures if you remove them.

Suppose that I have some header file `helper.h` where I define some inline function (say 'f'). Then I have `mylib.c` which calls the inline function ('f') and I export some other function (say 'g'). I have some header file `mylib.h` which declares 'g'. If I compile `mylib.c` to `mylib.lib`, and use `mylib.h`in my program, when I call 'g', it might go into `mylib.lib` to find the definition of 'g', which it will find. This definition of 'g' *may* not include the definition of 'f'. Nothing compels the compiler to inline 'f' inside 'g'. And `mylib.lib` will not have an externally visible definition for 'f'. If this happens, then it will fail at compile time with `Undefined symbols` because the new unit (which does not include 'helper.h') cannot find a definition for 'f'.

I don't think it can happen if you use the amalgamated version.

**Comment by lemire** [comment] 2021-11-25 16:59
Closing since the submitter has provided a fix. We were, indeed, in error.

> We have faced a compile bug

Most likely this was a *warning*, not a bug.

**Closed by lemire** 2021-11-25 16:59 UTC

**Comment by arthurkiller** [comment] 2021-11-29 11:48
Hi,  @lemire. Thx for your reply, explanation, and merging.

My question is not just about wether it can pass the compile.

AFAIK, `extern` means you want to export some symbols to the outer scope which `will not` generate the assemble code but an outer callable symbol (call) in the line while compiling. This will generate `call` in the assemble code. 
But `inline` means unfolding the function in place, which tells the compile to _generate_ the assemble code in calling place.

I think `extern` will do against what we want `inline` to do, even when it is necessary to pass the compile.

**Comment by lemire** [comment] 2021-11-29 14:47
> But inline means unfolding the function in place, which tells the compile to generate the assemble code in calling place. 

Please refer to the C99 standard: that's not what inline means. Compilers *may* do what you describe, but they are not required to do so. And, indeed, they do not always do it.

> I think extern will do against what we want inline to do, though it is necessary to pass the compile.

It is fairly easy to determine which functions is inlined. If you believe that the presence of the extern qualifiers in the code are harming the performance, please document it. You can run benchmarks or inspect compiler decisions (compilers will typically tell you if you pass the right flag).

Please do not speculate: provide measurements.
