### ISSUE TITLE
Roaring code uses <> instead of "" for its own headers.

### ISSUE THREAD

**Issue by davegomboc** [RoaringBitmap/CRoaring#231] opened 2020-07-04 08:34 UTC
The use of #include <roaring/roaring.h> instead of #include "roaring/roaring.h" is problematic when the system actually has CRoaring headers installed but one is trying to use a different version during development.

**Comment by lemire** [comment] 2020-07-04 19:30
Point taken. Do you want to issue a PR to fix this issue?

**Comment by lemire** [comment] 2020-12-07 13:32
User @thus modified our [includes from double-quote includes to bracketed includes](https://github.com/RoaringBitmap/CRoaring/commit/673946ff9390b166e083005abbc23d4fb50f5148). His rationale was as follow:

> Change the include paths in the header files to be able to include
"roaring/roaring.h" without specifying the include path



Someone else express to me his concerns:

> #include <roaring/roaring.h>  // The angle brackets indicate that this is a system header.
> versus
> #include "roaring/roaring.h"  // The quotation marks indicate that this is not a system header.
> The second is much preferable to the first.  The way things are now could become a big problem if you were to actually  have an old version of Roaring installed on your system, then you tried to compile a newer version that required incompatible header changes: you'd get the older, installed header versions instead of the new, local header versions.



Personally, I favour double-quote includes whenever possible but I'd like to better understand the trade-offs we are making.

**Comment by madscientist** [comment] 2020-12-07 13:56
I also would like to understand what circumstances would cause the incorrect headers to be found, and using which compiler.  The standard doesn't really well define the difference between "" and <> in #include.  However most compilers I'm aware of split header files into three "parts": searching the local directory, searching directories provided by -I, and searching predefined system header directories.

When you include with "", those three locations are all searched in that order.

When you include with <>, the first location (local directory) is skipped and the other two are searched in that order.

So, I'm not sure I see how using <> would cause the wrong CRoaring headers to be found.  Unless, I guess, you had them installed locally in a `roaring` subdirectory and you were relying on the "local directory" search to find them rather than adding `-I.` explicitly to the command line?

FYI GCC's handling of includes can be read about here: https://gcc.gnu.org/onlinedocs/cpp/Search-Path.html

**Comment by lemire** [comment] 2020-12-07 18:49
@davegomboc Can you elaborate on your issue?

**Comment by davegomboc** [comment] 2020-12-15 10:08
I think the note posted upstream already makes this clear, no?

> The way things are now could become a big problem if you were to actually have an old version of Roaring installed on your system, then you tried to compile a newer version that required incompatible header changes: you'd get the older, installed header versions instead of the new, local header versions.

For example, users of various Linux distributions install packages on their system, including programming headers.  So, some older version may be installed on a system (either manually installed by an installation script or via some actual package manager).  But, if then one also has a copy of the Git repo on their machine, the code is using <>, so when compilation is attempted the old headers that are installed on the system would be used, rather the current ones that are in the local copy of the repository.

**Comment by madscientist** [comment] 2020-12-15 17:09
What we're trying to understand is whether the note is actually correct, and if so how that manifests in an actual example.  I don't think that note is correct, or at least it's not the whole story.  I don't believe there's any way in any realistic scenario where the issue you are claiming, that old headers would be used incorrectly, would actually happen.  But maybe I'm missing something: that's why I'm trying to understand whether this problem was actually seen in real life and if so, get a description of the environment.

Let's try an example.  Say we have `/usr/include/roaring/` and also `/new/include/roaring/`.  Inside roaring/roaring.h we have an include of the roaring_types.h file.  Suppose that uses <> like now, so it would be:

```
#include <roaring/roaring_types.h>
```

Now you invoke your compiler with `-I/new/include`.  This all works fine: since `/new/include` is specified on the command line so it's always searched before `/usr/include`, even when looking for the internal `roaring/roaring_types.h`.

If we change the include above to "", it behaves exactly the same way!  So this scenario doesn't give us any reason to choose "" vs <>.

There's only one possible way that <> vs "" can make a difference: if you have the `roaring` directory as a local subdirectory of your source files and you don't add `-I.` explicitly to the compile line, but rather you're using the implicit "." search to handle it for you.

For example suppose you have `/usr/include/roaring/` and you also have `/my/src/roaring/.` and you have `/my/src/foo.c` and in `foo.c` you use `#include "roaring/roaring.h"`, and when you compile `foo.c` you **don't** add the current directory to the compile line with `-I`.  In this situation, compiling `cc -c -o foo.o foo.c` will correctly include `/my/src/roaring/roaring.h` but the `#include <roaring/roaring_types.h>` inside of `/my/src/roaring/roaring.h` will instead find the version in `/usr/include`.  That, of course, is bad.

However, just changing these to "" _won't fix this problem_!  Why?  Because "" looks in the working directory of the _including_ file, not the source file.  So, we have the file `/my/src/roaring/roaring.h` and it has `#include "roaring/roaring_types.h"`.  The compiler will first look for `roaring/roaring_types.h` in the directory of the header, which is `/my/src/roaring`, so it will look for `/my/src/roaring/roaring/roaring_types.h` which doesn't exist!  So, it will keep looking and it will _still_ find `/usr/include/roaring/roaring_types.h`.

The only way to make this scenario work correctly will be to change the "internal" header includes to remove the `roaring` directory.

In summary, we can do one of two things:

Leave things as they are where we have `#include <roaring/roaring_types.h>` and require that people always add `-I<pth>` to their compile line and never use the "implicit" path, or:

Change the headers to use "" and _also_ remove the subdirectories.  So we would change the contents of `roaring/roaring.h` from this:

```
#include <roaring/roaring_array.h>
#include <roaring/roaring_types.h>
#include <roaring/roaring_version.h>
```

to this:

```
#include "roaring_array.h"
#include "roaring_types.h"
#include "roaring_version.h"
```

It's true that this is _marginally_ safer in some obscure situations, that I highly doubt anyone really runs into in real life, and which can be mitigated by adding the `-I.` to the compile line.  But if we wanted to do it we certainly could, as long as it's done correctly.

In my projects I use the amalgamation so I don't run into any issues like this anyway :) :)

**Comment by madscientist** [comment] 2020-12-15 17:34
Of course it doesn't have to be a subdirectory... you could have `/my/include/roaring/.` and `/my/src/foo.c`, then in `foo.c` you use a relative path like `#include "../include/roaring/roaring.h"` so you don't need to add `-I/my/include` to the compile line.  Then you'd run into a problem with <> that would be mitigated by using "" and removing the subdirectories.  The key is that the only way you get the wrong thing is if you don't add the roaring directory you want to the compile line with `-I` but instead locate it indirectly some other way.

**Comment by davegomboc** [comment] 2020-12-16 06:56
> Because "" looks in the working directory of the including file, not the source file.

Maybe; maybe not, and that may not be the only place that is searched.  Differences in behaviour between different compiler preprocessors are allowed by the C and C++ standards.  GCC may use different include directive resolution rules than MSVC (https://docs.microsoft.com/en-us/cpp/preprocessor/hash-include-directive-c-cpp?view=msvc-160), and some embedded system compiler may use different rules again.  For instance, MSVC is documented to search:

> 2) In the directories of the currently opened include files, in the reverse order in which they were opened. The search begins in the directory of the parent include file and continues upward through the directories of any grandparent include files.

Notwithstanding variations in behaviour, It is nonetheless the general convention that "" is used for header files that are part of the program that is being compiled.  In my view, it is natural and expected that someone should safely be able to download and immediately compile the code without having to specify -I, even if they have a different version of those header files installed already.

Please do feel free to close this as won't fix if you don't think it's worth it to address.

**Comment by madscientist** [comment] 2020-12-16 13:48
You are right that the standard doesn't declare the exact behavior, but all compilers I'm aware of work that way.  Yes, it's true that MSVC also adds other directories but neither GCC nor clang do so which means we cannot rely on that behavior when writing portable code: we must assume the more strict behavior.

I have no problems with the change (but someone needs to create the PR!!): it's clear that using "" causes correct behavior in strictly more situations than using <>... even if those situations seem highly unlikely to happen in real life (at least, to me).  I just wanted to be sure that whomever attempted it made the _right_ change, because just switching from <> to "" alone will never (at least not with GCC or clang) actually make any difference at all.

**Comment by lemire** [comment] 2020-12-16 15:50
Note that we switched from "" to <> because some users did not want to pick up the local roaring headers by mistake.

> Notwithstanding variations in behaviour, It is nonetheless the general convention that "" is used for header files that are part of the program that is being compiled. 

CRoaring is a software library that many developers install on their systems. Many software libraries use the <> include header convention. For example, C++ Boost does. I have defaulted to ""  myself, and it seems to be more common in the projects I am involved with, but I am far from certain that using <> is wrong for a software library. It seems common enough.

**Comment by madscientist** [comment] 2020-12-16 18:48
> Note that we switched from "" to <> because some users did not want to pick up the local roaring headers by mistake.

Just as I don't see how switching from <> to "" would help much in a realistic situation, I don't see how the original switch from "" to <> would help anyone "not pick up local headers by mistake".  If the user puts a `-I<dir>` on their compiler line, they _WILL_ get the right roaring headers, regardless of whether we use <> or "" inside roaring headers.

The issue isn't really which roaring.h header they will pick up: we can't control that.  In the user's code they choose whether they use <roaring/roaring.h> or "roaring/roaring.h" and they choose what compiler options to use.

The thing we control is the "inner includes": includes inside roaring/roaring.h like roaring/roaring_types.h (and other internal headers).  Regardless of what the user prefers, local vs. system, we definitely don't want to use a different/inconsistent set of "inner headers" that don't match the roaring/roaring.h file they included.

**Comment by lemire** [comment] 2020-12-22 22:46
The issue has been discussed. I am going to close it. I think that if anyone wants to change the current state of affairs, they have to build a strong case.

**Closed by lemire** 2020-12-22 22:46 UTC
Labels: question
