### ISSUE TITLE
Faster contains operation in array containers

### ISSUE THREAD

**Issue by WojciechMula** [RoaringBitmap/CRoaring#98] opened 2017-05-02 15:45 UTC
Here is the change you can check out: https://github.com/WojciechMula/CRoaring/commit/6541bc70757351e7cc61e78df339a89eabf071d8

As the commit messages states, it's a mix of binary search and linear search. Whenever range in binary search becomes smaller than some (small) threshold, we use linear search on this range. My experiments show that for relative small tables linear search wins. You can take a look at my old article http://0x80.pl/articles/simd-search.html#binary-search-with-fallback-to-linear-search-new.

Below are benchmarks from Skylake and my old Westmere CPU. On Skylake we get nearly 1.5 speedup, on Westmere -- 1.2.

```
Original

Skylake:  contains_test(B):  147.80 cycles per operation
Westmere: contains_test(B):  128.83 cycles per operation

Modified (threshold = 8 items)

Skylake:  contains_test(B):  101.91 cycles per operation
Westmere: contains_test(B):  105.50 cycles per operation

Modified (threshold = 16 items)

Skylake:  contains_test(B):   97.91 cycles per operation
Westmere: contains_test(B):  104.34 cycles per operation
```

**Comment by lemire** [comment] 2017-05-02 21:20
Benchmarking correctly is important. Can you do this for me? Go to your CRoaring repo:

```
$ git fetch upstream // do whatever is necessary for this to work
$ git pull upstream master
$ mkdir build
$ cd build
$ cmake ..
$ ./benchmarks/real_bitmaps_contains_benchmark  ../benchmarks/realdata/weather_sept_85
```

Test with and without your optimization. What do you get?

**Comment by lemire** [comment] 2017-05-02 21:21
Of course, you can try different datasets, we have several to choose from.

**Comment by WojciechMula** [comment] 2017-05-03 09:28
Here is a comparison: the first column are cycles from the current trunk, the second column cycles from my modification, the third is difference and the last one is speed-up. There's no speedup at all.

```

file benchmarks/realdata/census1881
creating    :   12537218    12539370        2152  0.9998
copy&free   :     634848      649318       14470  0.9777
and         :     230348      231636        1288  0.9944
or          :    1499952     1506252        6300  0.9958
and in-place:     332026      331510        -516  1.0016
or in-place :    2547394     2557356        9962  0.9961
iterating   :   10374950    11444648     1069698  0.9065

file benchmarks/realdata/census1881_srt
creating    :    8584010     8609234       25224  0.9971
copy&free   :     413710      416418        2708  0.9935
and         :     202392      212106        9714  0.9542
or          :    1243628     1253994       10366  0.9917
and in-place:     294132      295388        1256  0.9957
or in-place :    1363550     1362964        -586  1.0004
iterating   :   10549344    10686490      137146  0.9872

file benchmarks/realdata/census-income
creating    :   69744048    69707060      -36988  1.0005
copy&free   :     412294      411800        -494  1.0012
and         :    2674986     2672950       -2036  1.0008
or          :    3329500     3338044        8544  0.9974
and in-place:    5913544     5933186       19642  0.9967
or in-place :    4207544     4218088       10544  0.9975
iterating   :  118965794   119340522      374728  0.9969

file benchmarks/realdata/census-income_srt
creating    :   63029972    63337276      307304  0.9951
copy&free   :     422466      421556        -910  1.0022
and         :    1908674     1910682        2008  0.9989
or          :    3200212     3200666         454  0.9999
and in-place:    2201024     2211404       10380  0.9953
or in-place :    3905442     3958332       52890  0.9866
iterating   :  102843824   103220772      376948  0.9963

file benchmarks/realdata/uscensus2000
creating    :    1341756     1326874      -14882  1.0112
copy&free   :     246716      244234       -2482  1.0102
and         :      71748       70684       -1064  1.0151
or          :     716404      713546       -2858  1.0040
and in-place:     185796      185504        -292  1.0016
or in-place :     727014      724398       -2616  1.0036
iterating   :     123392      121472       -1920  1.0158

file benchmarks/realdata/weather_sept_85
creating    :  137721998   137500582     -221416  1.0016
copy&free   :    1606798     1579606      -27192  1.0172
and         :    9559206     9524592      -34614  1.0036
or          :   13216752    13215172       -1580  1.0001
and in-place:   24634288    24645240       10952  0.9996
or in-place :   17943106    17897032      -46074  1.0026
iterating   :  220466118   222224708     1758590  0.9921

file benchmarks/realdata/weather_sept_85_srt
creating    :  165851614   165578936     -272678  1.0016
copy&free   :    1298474     1298330        -144  1.0001
and         :    3532692     3522546      -10146  1.0029
or          :    6980322     6973328       -6994  1.0010
and in-place:    4144840     4138178       -6662  1.0016
or in-place :    9918428     9899910      -18518  1.0019
iterating   :  273738512   274581628      843116  0.9969

file benchmarks/realdata/wikileaks-noquotes
creating    :    4783588     4770446      -13142  1.0028
copy&free   :     469866      469426        -440  1.0009
and         :     845374      844084       -1290  1.0015
or          :    2127670     2134572        6902  0.9968
and in-place:     788818      794964        6146  0.9923
or in-place :    2374372     2375624        1252  0.9995
iterating   :    2857146     3122906      265760  0.9149

file benchmarks/realdata/wikileaks-noquotes_srt
creating    :    4867622     4926320       58698  0.9881
copy&free   :     337100      325036      -12064  1.0371
and         :     472930      473144         214  0.9995
or          :    1445694     1455962       10268  0.9929
and in-place:     368072      369872        1800  0.9951
or in-place :    1546966     1553188        6222  0.9960
iterating   :    4258680     4356404       97724  0.9776
```

**Comment by lemire** [comment] 2017-05-03 14:47
@WojciechMula 

I think you ran ``benchmarks/real_bitmaps_contains_benchmark``  but what I actually suggested  is ``benchmarks/real_bitmaps_contains_benchmark``. It is a new benchmark program that I created specifically so we can discuss and review your optimization.

Can  you rerun your tests with ``benchmarks/real_bitmaps_contains_benchmark``? 

Let me share some of my results.

Original code:

```
$ ./benchmarks/real_bitmaps_contains_benchmark ../benchmarks/realdata/weather_sept_85
Constructing 200  bitmaps.
........................................................................................................................................................................................................
Loaded 200 bitmaps from directory ../benchmarks/realdata/weather_sept_85
Creating 200 bitmaps took 147849150 cycles
Quartile queries on 200 bitmaps took 37462 cycles
```

Let me now change the code to patch in your optimization:

```
$ git diff
diff --git a/include/roaring/containers/array.h b/include/roaring/containers/array.h
index 5dbbd82..a59f952 100644
--- a/include/roaring/containers/array.h
+++ b/include/roaring/containers/array.h
@@ -299,7 +299,29 @@ static inline bool array_container_remove(array_container_t *arr,
 /* Check whether x is present.  */
 inline bool array_container_contains(const array_container_t *arr,
                                      uint16_t pos) {
-    return binarySearch(arr->array, arr->cardinality, pos) >= 0;
+//    return binarySearch(arr->array, arr->cardinality, pos) >= 0;
+    // binary search with fallback to linear search for short ranges
+    int32_t low = 0;
+    int32_t high = arr->cardinality - 1;
+    while (high - low > 16) {
+        int32_t middleIndex = (low + high)/2;
+        uint16_t middleValue = arr->array[middleIndex];
+        if (middleValue < pos) {
+            low = middleIndex + 1;
+        } else if (middleValue > pos) {
+            high = middleIndex - 1;
+        } else {
+            return true;
+        }
+    }
+
+    for (int i=low; i <= high; i++) {
+        if (arr->array[i] == pos) {
+            return true;
+        }
+    }
+    return false;
+
 }

 /* Returns the smallest value (assumes not empty) */
```




```
$ make
$ ./benchmarks/real_bitmaps_contains_benchmark ../benchmarks/realdata/weather_sept_85
Constructing 200  bitmaps.
........................................................................................................................................................................................................
Loaded 200 bitmaps from directory ../benchmarks/realdata/weather_sept_85
Creating 200 bitmaps took 147821560 cycles
Quartile queries on 200 bitmaps took 82560 cycles
```

So the change lead to a significant increase in the running time. From  37462 cycles to 82560 cycles.

What I am getting at is that your small change is actually very detrimental to the performance.

Now, I would prefer if you ran the benchmark on your own, of course.

Note that I have investigated some non-trivial vectorized binary search code, see https://github.com/lemire/Code-used-on-Daniel-Lemire-s-blog/tree/master/extra/simd/binsearch  It helps but only when the data is in cache. However, with a "contains" query, you should not assume that teh data is in cache. If you are careful to design the benchmark so that the data is not evidently in L1 cache, then you find that it is very hard to improve on the textbook binary search.

I am  not saying that we cannot do better than a textbook binary search... but I am saying that doing so when the data is not in cache is harder than it might seem.

**Comment by owenkaser** [comment] 2017-05-03 16:56
@lemire One reason for the increase in cycles appears to be the division by two, versus the right shift in the binary search.  I have not looked at the assembly output, but perhaps the issue is that we are working with signed numbers and the compiler can't do the intended strength reduction.  Anyway, when I try the code suggested by @WojciechMula and replace the division, the increase in cycles is still there, but more modest.

Since this is all built by cmake, I am just trusting that -O3 is being used with gcc...

**Comment by lemire** [comment] 2017-05-03 17:07
@owenkaser  is definitively right.

The signed division is costing a lot.

Here is a faster version:

```
$ git diff
diff --git a/include/roaring/containers/array.h b/include/roaring/containers/array.h
index 5dbbd82..fef037f 100644
--- a/include/roaring/containers/array.h
+++ b/include/roaring/containers/array.h
@@ -299,7 +299,29 @@ static inline bool array_container_remove(array_container_t *arr,
 /* Check whether x is present.  */
 inline bool array_container_contains(const array_container_t *arr,
                                      uint16_t pos) {
-    return binarySearch(arr->array, arr->cardinality, pos) >= 0;
+//    return binarySearch(arr->array, arr->cardinality, pos) >= 0;
+    // binary search with fallback to linear search for short ranges
+    int32_t low = 0;
+    int32_t high = arr->cardinality - 1;
+    while (high - low > 16) {
+        int32_t middleIndex = (low + high)>>1;
+        uint16_t middleValue = arr->array[middleIndex];
+        if (middleValue < pos) {
+            low = middleIndex + 1;
+        } else if (middleValue > pos) {
+            high = middleIndex - 1;
+        } else {
+            return true;
+        }
+    }
+
+    for (int i=low; i <= high; i++) {
+        if (arr->array[i] == pos) {
+            return true;
+        }
+    }
+    return false;
+
 }

 /* Returns the smallest value (assumes not empty) */
```

```
$ ./benchmarks/real_bitmaps_contains_benchmark ../benchmarks/realdata/weather_sept_85
Constructing 200  bitmaps.
........................................................................................................................................................................................................
Loaded 200 bitmaps from directory ../benchmarks/realdata/weather_sept_85
Creating 200 bitmaps took 148152738 cycles
Quartile queries on 200 bitmaps took 53294 cycles
```

So 53294 cycles vs 37462 cycles, that's still a huge difference.

**Comment by lemire** [comment] 2017-05-03 17:24
Note that in Java, Roaring use exactly the kind of algorithm @WojciechMula  proposes... We call it ``hybridUnsignedBinarySearch`` and it is faster.

https://github.com/RoaringBitmap/RoaringBitmap/blob/bd7898a6b195688aaedb374e24b55df84d5b9979/src/main/java/org/roaringbitmap/Util.java#L274

So it is a surprise to me that it does not work in C.

The logic of why it should be faster is intuitively clear. 

So what gives?

**Comment by owenkaser** [comment] 2017-05-04 00:24
1.  It does seem really hard to beat textbook binary search on the benchmark.    I wonder if somehow Intel tunes its microarchitectures with textbook binary search as a key benchmark!

2. gcc 4.8.4 with -O3 generates a logical right shift for "x/2U" and "x/2" if x is unsigned.  But if x is signed, there is some fixup needed since an arithmetic right shift isn't quite equal to x/2 if x is negative.  So it generates 3 extra instructions besides the shift.  It does not use a divide instruction.  But it is still more expensive than the code sequence for "x>>1".

**Comment by lemire** [comment] 2017-05-04 01:00
@owenkaser 

> It does seem really hard to beat textbook binary search on the benchmark. I wonder if somehow Intel tunes its microarchitectures with textbook binary search as a key benchmark!

I think it has to be related to the interplay with the cache because if you do ensure that the whole array is scanned before you do the binary search, then you can beat the textbook binary search. But I don't see how simply finishing off the search with a linear scan can bring about such a large penalty.

Could be that it causes an expensive cache miss?


> gcc 4.8.4 with -O3 generates a logical right shift (...)

Your observation is very important. In Java,  not trusting the compiler, I always manually introduce the shifts. I think I had somehow assumed that optimizing C compilers would turn divisions by two into shifts... with little overhead. 

Note that you can explore assembly output for a wide range of compilers using Godbolt's tool... https://godbolt.org/g/WLicOe
With it, we can establish that this is true with all compilers.

**Comment by WojciechMula** [comment] 2017-05-05 16:19
I didn't aware that signed division has got such big overhead. Something new learned.

**Comment by WojciechMula** [comment] 2017-05-05 17:06
@lemire I run your new benchmarks and it's clear that my modification doesn't bring any speedup. It's surprising, as the benchmark for synthetic data shows significant speedup. To be honest, I don't get why there's so huge difference.

**Comment by lemire** [comment] 2017-05-05 17:13
I also do not understand the performance of a binary search and it has been bothering me for some time.

If you look at the benchmark I wrote, it hits a bitmap 3 times at different locations, then it moves to the next one and so forth. This makes cache misses likely.

It is easy to write a synthetic benchmark that does not incur many likely cache misses.

Of course, we want good all around performance.

**Comment by owenkaser** [comment] 2017-05-05 20:14
At least with my compiler, I do not think that the given binary search (with right shift) gets compiled into comparable machine code as when binarySearch is invoked and inlined.  It seems to be a little less efficient.   As an experiment I changed the while condition to (high - low >= 0) to more or less match binarySearch and commented out the linear search.     The result should have been more or less equivalent, but was consistently a bit slower.  I thought that the const-ness of the array parameter in binarySearch might have made the difference, and indeed adding 
    const uint16_t *const thearray = arr->array;
and then loading middleValue from thearray
  seems to give results that (subject to a little perf measurement noise) seem to match.  Maybe the compiler had  thought it would need to dereference arr whenever it got middleValue.   Or maybe it just decided to generate slightly different machine code for some other reason.

However, I have not checked the actual machine code  now to see whether it is the same.

**Comment by lemire** [comment] 2017-05-05 20:51
@owenkaser 

>  As an experiment I changed the while condition to (high - low >= 0) to more or less match binarySearch and commented out the linear search. The result should have been more or less equivalent, but was consistently a bit slower.

It is true that ``high >= low`` is not equivalent as far as the compiler is concerned with ``high - low >= 0`` but this might have to do with overflow. [I cannot verify that this alone impacts the performance in any way in a synthetic benchmark](https://github.com/lemire/Code-used-on-Daniel-Lemire-s-blog/blob/master/extra/simd/binsearch/simdbinsearch16.c).

You can see how it gets compiled using different compilers:

https://godbolt.org/g/LezPbJ

https://godbolt.org/g/lT167d

**Comment by owenkaser** [comment] 2017-05-05 20:56
I am not sure that I trust the Godbolt tool totally  Perhaps I do not know the full set of compiler flags that cmake will use.    With an earlier use and -O3, it showed me some code for binary search that had not been unrolled, but the machine code as annotated by perf seemed to have been unrolled.

**Comment by lemire** [comment] 2017-05-05 21:05
@owenkaser  After calling ``cmake`` call ``make VERBOSE=1`` instead of ``make``. This will give you the full commands and you will be able to know exactly which flags are used. I expect that you will not find the result surprising.

**Comment by lemire** [comment] 2017-09-12 22:40
Closing for now.

**Closed by lemire** 2017-09-12 22:40 UTC
