### ISSUE TITLE
Error while building 

### ISSUE THREAD

**Issue by vivek425ster** [RoaringBitmap/CRoaring#20] opened 2016-03-24 18:36 UTC
I get the following error when i run ``make`` command. ``cmake ..`` ran successfully without any errors
I am working on ubuntu 32 bit system.
````
[  4%] Building C object CMakeFiles/roaring.dir/src/bitset_util.c.o
/home/vivek/CRoaring/src/bitset_util.c: In function ‘bitset_set_list_withcard’:
/home/vivek/CRoaring/src/bitset_util.c:725:5: error: ‘asm’ operand has impossible constraints
     __asm volatile(
     ^
/home/vivek/CRoaring/src/bitset_util.c:740: confused by earlier errors, bailing out
Preprocessed source stored into /tmp/ccbJIlS2.out file, please attach this to your bugreport.
make[2]: *** [CMakeFiles/roaring.dir/src/bitset_util.c.o] Error 1
make[1]: *** [CMakeFiles/roaring.dir/all] Error 2
make: *** [all] Error 2
```
Contents of ``/tmp/ccbJIIS2.out``: http://pastebin.com/RKzTFjd4

**Comment by lemire** [comment] 2016-03-24 19:24
@vivek425ster 

Thanks. 

Please consider our objective...

> The primary goal of the CRoaring is to provide a high performance low-level implementation that fully take advantage of the latest hardware.

One can already use Roaring on a great variety of platforms through the Java version. The purpose of writing a C version is to get superior performance.


We expect a recent Intel processor (Haswell or better):

https://github.com/RoaringBitmap/CRoaring#requirements

As an aside, on a regular PC, there seems to be no good reason in 2016 to use a 32-bit version of Ubuntu? I quote...

> To no surprise compared to our 32-bit vs. 64-bit benchmarking over nearly the past decade, the 64-bit version of Ubuntu generally delivers superior performance over 32-bit Ubuntu. This strong 64-bit performance is present even when using an old Intel Core 2 Duo system with just 1GB of memory. The reasons for avoiding 64-bit Linux are generally moot these days with Flash, Java, and other applications now running just fine on x86_64 distributions. http://www.phoronix.com/scan.php?page=article&item=ubuntu_x86_1304&num=4

I guess it is possible that on some old PCs, the 32-bit PC architecture might be best, but such old machines are not our concern at this point. (To be clear, there is absolutely nothing wrong with using old machines... it is just not a target for this library.)

If you have a non-Intel architecture (e.g., ARM), then this library cannot be expected to work right now... though we would certainly welcome contributors who want to port it. Even there, we would probably focus on the most recent processors.

**Comment by nkurz** [comment] 2016-03-24 22:00
We probably should put in a configuration check that puts up a prominent
warning when used on untested systems.   If not clear from Daniel's
response, the issue is that the source includes 64-bit x86 assembly, and
there just isn't any way to for a 32-bit x86 system to run it.  A 32-bit
version or a plain C fallback could be written, but the performance
wouldn't be as good, and it's not currently a high priority for the
project.

That said, I would be interested in Daniel's question about why you are
running a 32-bit OS.  It's not just you, I'm generally surprised at how
prevalent such systems still are.   Do you have a particular reason for
running it?

--nate

**Comment by lemire** [comment] 2016-03-24 22:38
@nkurz 


>  A 32-bit version or a plain C fallback could be written, but the performance
wouldn't be as good

We do have plain C versions for many things, if only because to know that assembly is needed, you need to compare it with plain C.

**Comment by vivek425ster** [comment] 2016-03-25 04:30
@lemire @nkurz Thanks you for your response.
I am working on a project which currently works on 32 bit systems only. I am doing a dynamic taint flow analysis of a binary file using PIN, for storing the taint flow information, i am trying to use Roaring Bitset so that the performance is better than that provided by set.

**Comment by lemire** [comment] 2016-03-26 02:12
@vivek425ster 

This library is not ready for production use. I have updated the README.md accoringly. Please see http://roaringbitmap.org for other versions of Roaring.

If you can use C++, there is a version of EWAH that is well supported  https://github.com/lemire/EWAHBoolArray 

In C, you can use Git's very own EWAH https://github.com/git/git/tree/master/ewah This is very, very mature and very robust code. 

Both git and EWAHBoolArray should work fine on 32-bit systems.

I am closing this. Reopen if you disagree.

**Closed by lemire** 2016-03-26 02:12 UTC
