### ISSUE TITLE
amalgamation_demo.c is named incorrectly

### ISSUE THREAD

**Issue by openastexviewer** [RoaringBitmap/CRoaring#66] opened 2016-10-24 08:54 UTC
Very minor... Dont know if this is deliberate but amalgamation_demo.c/cpp is named almagamation_demo.c

**Comment by lemire** [comment] 2016-10-24 11:42
Can you elaborate?

The script generates source files named amalgamation_demo.c and amalgamation_demo.cpp.

**Comment by openastexviewer** [comment] 2016-10-24 11:57
I downloaded on Friday. Running as follows (I've slightly truncated the output below).

The filename seems to be set as below at line 86 and other places. I checked the github zip that I downloaded and it seems to be in there as well.

```
DEMOC="almagamation_demo.c"
echo "Creating ${DEMOC}..."

```
Output

```
./amalgamation.sh
We are about to amalgamate all CRoaring files into one source file.
See https://www.sqlite.org/amalgamation.html and https://en.wikipedia.org/wiki/Single_Compilation_Unit for rationale.
Creating roaring.h...
Creating roaring.c...
Creating almagamation_demo.c...
Done with C amalgamation. Proceeding with C++ wrap.
Creating roaring.hh...
Creating almagamation_demo.cpp...
Done with C++.
Done with all files generation.

The interface is found in the file 'include/roaring/roaring.h'.

Try :
cc -march=native -O3 -std=c11  -o almagamation_demo almagamation_demo.c  && ./almagamation_demo

For C++, try :
c++ -march=native -O3 -std=c++11 -o almagamation_demo almagamation_demo.cpp  && ./almagamation_demo

```

**Comment by lemire** [comment] 2016-10-24 13:06
Yes. The script creates two files, ``almagamation_demo.c`` and ``almagamation_demo.cpp`` that the user can compile as a naive test that everything is in order. As the names suggests, these can be used to build simple demo executables.

I'm going to close this. If you have a concern,  please reopen and state clearly what the problem is.

**Comment by openastexviewer** [comment] 2016-10-24 13:17
Sorry as I have started I will try one more time ;-)

The file name should be amalgamation_demo.c not almagamation_demo.c, I only only spotted it because typing 

`./am<tab>` in a shell window doesn't list the executable (as it does not begin with am). Hopefully it is clear below (amal not alma at the start)

```
amalgamation_demo.c
almagamation_demo.c     -- this is what is produced not the above (s/alma/amal/)
 ^^^

```
The filename is typed incorrectly in the .sh file at the line I indicated above (and some other locations).

**Comment by lemire** [comment] 2016-10-24 13:19
Ah!

**Comment by lemire** [comment] 2016-10-24 13:21
Sorry for not understanding your report... Fixed hopefully...

https://github.com/RoaringBitmap/CRoaring/commit/3aee00a4c80d5c6bc5734780b030390b51120500

**Closed by lemire** 2016-10-24 13:21 UTC

**Comment by openastexviewer** [comment] 2016-10-24 13:25
No problem. I only mention it as I spent a few minutes trying to figure out why Cygwin didn't think the file was executable... (and of course it works if you cut and paste the command example as it is spelled consistently everywhere).

**Comment by lemire** [comment] 2016-10-24 13:49
@openastexviewer Yes. The issue was very much a valid one.
