### ISSUE TITLE
c(not c++) support for 64-bit integers

### ISSUE THREAD

**Issue by lambgong** [RoaringBitmap/CRoaring#232] opened 2020-07-20 14:30 UTC

**Comment by lemire** [comment] 2020-07-20 15:18
This could be achieved inexpensively by wrapping the C++ API with a C API.

Pull requests invited.

**Comment by guymolinari** [comment] 2020-07-28 13:45
I do have a partial implementation of the BSI library.   Will PR it in the next few weeks.

**Comment by madscientist** [comment] 2020-10-22 16:40
Is this different from issue #1?

**Comment by lemire** [comment] 2020-10-22 16:54
Quite right. This is a duplicate. Closing in favour of https://github.com/RoaringBitmap/CRoaring/issues/1

**Comment by lemire** [comment] 2020-10-22 16:55
Note that this is supported already via the C++ interface. The core C code is 32-bit only, by design.

**Closed by lemire** 2020-10-22 16:55 UTC
