### ISSUE TITLE
About `Roaring64Map` and `RoaringMap` and possible future extensions

### ISSUE THREAD

**Issue by cubicYYY** [RoaringBitmap/CRoaring#651] opened 2024-08-16 13:01 UTC
My query is why some of the APIs for the 64-bit version and the 32-bit version don't seem to be exactly the same?

And, if one wants to implement other versions (e.g. `Roaring128Map` or `Roaring16Map`), is this easy to do? If not, what are the barriers that prevent such an extension?

Thanks in advance for your answers.

**Comment by mapleFU** [comment] 2024-08-16 13:21
Maybe related: https://github.com/RoaringBitmap/CRoaring/issues/629

**Comment by lemire** [comment] 2024-08-16 13:21
> My query is why some of the APIs for the 64-bit version and the 32-bit version don't seem to be exactly the same?


Duplicate of https://github.com/RoaringBitmap/CRoaring/issues/549

The gap has closed significantly.

> And, if one wants to implement other versions (e.g. Roaring128Map or Roaring16Map), is this easy to do? If not, what are the barriers that prevent such an extension?


There is no barrier other than the work required. Pull requests invited. Please consider contributing.

**Comment by lemire** [comment] 2024-08-16 13:22
I have closed this issue as it is a duplicate of existing issues.

**Closed by lemire** 2024-08-16 13:21 UTC
